### ISSUE TITLE
access violation in avs 2.6

### ISSUE THREAD

**Issue by realfinder** [Asd-g/TMM2#1]
ColorBars(width=640, height=480, pixel_type="yv12")
tmm2

![image](https://user-images.githubusercontent.com/2512153/86087391-c4f8c380-baac-11ea-8d56-6280d2b664c3.png)

**Comment by Asd-g** [comment]
Please try 0.1.5.

**Comment by realfinder** [comment]
seems work fine now in avs 2.6, thanks
