### ISSUE TITLE
adding HBD

### ISSUE THREAD

**Issue by realfinder** [Asd-g/TMM2#2]
hi

since pinterf added HBD to Tdeint is it possible to support HBD in TMM2 as well?

thanks

**Comment by Asd-g** [comment]
I will take a look. It would be probably easier to port [VapouSynth TMM](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TDeintMod).

**Comment by Asd-g** [comment]
You can check [vsTMM](https://github.com/Asd-g/AviSynth-vsTMM).

**Comment by realfinder** [comment]
thanks
